from typing import List, Dict, TypedDict

class ResearchAgentState(TypedDict):
    """
    Maintains the global shared state across all agent nodes 
    within the LangGraph research workflow pipeline.
    """
    # The primary query or topic provided by the user
    user_query: str
    
    # Internal plan generated by the Planner Node to track search tasks
    research_plan: List[str]
    
    # List of queries that have already been executed to prevent loops
    executed_queries: List[str]
    
    # Aggregated raw texts gathered from web search and scraping tools
    raw_web_data: List[str]
    
    # Financial metrics retrieved in string/JSON format
    financial_data: List[str]
    
    # Analysis outputs generated from multi-modal vision assets
    vision_data: List[str]
    
    # Top verified contexts extracted from ChromaDB after Reranking
    refined_contexts: List[str]
    
    # The current draft of the research report written by the Writer Node
    current_report: str
    
    # Review remarks or validation issues provided by the Editor Node
    editor_feedback: Dict[str, str]
    
    # Control flags determining step transitions (e.g., "approve", "revise", "search")
    next_step: str